### ISSUE TITLE
just a suggestion

### ISSUE THREAD

**Issue by rcrooks** [muchirijane/Nairobi-Night-Color-Theme#1]
@muchirijane Love the colors! Just a small suggestion: could you make the brackets for HTML tags a bit darker so that they contrast with the tag name? If you're open to it, I'm happy to do it and raise a pull request.

Best,
Robert

**Comment by muchirijane** [comment]
Hey, @rcrooks thank you so much for your feedback. I have added a darker blue colour. Reload the extension to see the update. For more create another issue. 
Thanks :)

**Comment by rcrooks** [comment]
HI @muchirijane - looks great! thanks so much.

**Comment by muchirijane** [comment]
Thank you for your feedback. 💯🙌🏽
